package br.com.rango.ngc.util.outros.email;

public class RecuperarSenhaEmail
{	
	public static String getEmailRecuperarSenha(String link) 
	{
		String msg = "";

		msg += 	"<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"                                                                                                                                                                          ";
		msg += 	"	style=\"width: 600px\">                                                                                                                                                                                                                        ";
		msg += 	"	<tbody>                                                                                                                                                                                                                                        ";
		msg += 	"		<tr>                                                                                                                                                                                                                                       ";
		msg += 	"			<td bgcolor=\"#c7191a\" style=\"padding: 10px;\">                                                                                                                                                                                      ";
		msg += 	"				<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"                                                                                                                                                                            ";
		msg += 	"					style=\"width: 100%\">                                                                                                                                                                                                         ";
		msg += 	"					<tbody>                                                                                                                                                                                                                        ";
		msg += 	"						<tr>                                                                                                                                                                                                                       ";
		msg += 	"						                                                                                                                                                                                                                           ";
		msg += 	"							<td style=\"width: 58px; text-align: center;\"><img src=\"http://1rango.com.br/img/mail_cad/logo1rango.png\" border=\"0\"></td>                                                                                        ";
		msg += 	"						</tr>                                                                                                                                                                                                                      ";
		msg += 	"					</tbody>                                                                                                                                                                                                                       ";
		msg += 	"				</table>                                                                                                                                                                                                                           ";
		msg += 	"			</td>                                                                                                                                                                                                                                  ";
		msg += 	"		</tr>                                                                                                                                                                                                                                      ";
		msg += 	"		<tr>                                                                                                                                                                                                                                       ";
		msg += 	"			<td>                                                                                                                                                                                                                                   ";
		msg += 	"				<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"                                                                                                                                                           ";
		msg += 	"					style=\"width: 512px\">                                                                                                                                                                                                        ";
		msg += 	"					<tbody>                                                                                                                                                                                                                        ";
		msg += 	"						<tr>                                                                                                                                                                                                                       ";
		msg += 	"							<td style=\"font-family: Times; color: black; font-size: 40px; font-weight: bold; font-style: italic; text-align: center; padding: 10 0 10 0;\">                                                                       ";
		msg += 	"								                                                                                                                                                                                                                   ";
		msg += 	"							</td>                                                                                                                                                                                                                  ";
		msg += 	"						</tr>                                                                                                                                                                                                                      ";
		msg += 	"						<tr>                                                                                                                                                                                                                       ";
		msg += 	"					                                                                                                                                                                                                                               ";
		msg += 	"						</tr>                                                                                                                                                                                                                      ";
		msg += 	"						<tr>                                                                                                                                                                                                                       ";
		msg += 	"							<td style=\"font-family: Times; color: #777777; font-size: 20px; padding: 10 0 10 0;\">                                                                                                                                ";
		msg += 	"								Olá, <b> Carlos Diego</b>, <br/>                                                                                                                                                                                   ";
		msg += 	"								Parece que você solicitou a recuperação de senha do 1Rango! <br/>                                                                                                                                                  ";
		msg += 	"								Se você não solicitou sua senha, ignore este e-mail e nada acontecerá. <br/><br/>                                                                                                                                  ";
		msg += 	"							</td>                                                                                                                                                                                                                  ";
		msg += 	"						</tr>                                                                                                                                                                                                                      ";
		msg += 	"						<tr>                                                                                                                                                                                                                       ";
		msg += 	"							<td align=\"center\" style=\"padding: 10px;\">                                                                                                                                                                         ";
		msg += 	"								<a href=\"" + link + "\" style=\"background: #85aa27; padding: 10.5px 21px; border-radius: 5px; color: #ffffff; font-size: 14px; font-family: Arial,sans-serif; text-decoration: none; vertical-align: middle;\">                   ";
		msg += 	"									Alterar Senha                                                                                                                                                                                                  ";
		msg += 	"								</a>                                                                                                                                                                                                          ";
		msg += 	"							</td>                                                                                                                                                                                                                  ";
		msg += 	"						</tr>                                                                                                                                                                                                                      ";
		msg += 	"						                                                                                                                                                                                                                           ";
		msg += 	"						<tr>                                                                                                                                                                                                                       ";
		msg += 	"							<td style=\"font-family: Times; text-align: center; color: #777777; font-size: 15px; padding: 10 0 10 0;\">                                                                                                            ";
		msg += 	"								Lembre-se: Nunca divulgue sua senha a ninguém.								                                                                                                                                       ";
		msg += 	"							</td>                                                                                                                                                                                                                  ";
		msg += 	"						</tr>                                                                                                                                                                                                                      ";
		msg += 	"					</tbody>                                                                                                                                                                                                                       ";
		msg += 	"				</table>                                                                                                                                                                                                                           ";
		msg += 	"			</td>                                                                                                                                                                                                                                  ";
		msg += 	"		</tr>                                                                                                                                                                                                                                      ";
		msg += 	"		<tr>                                                                                                                                                                                                                                       ";
		msg += 	"			<td bgcolor=\"#c7191a\">                                                                                                                                                                                                               ";
		msg += 	"				<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"                                                                                                                                                                            ";
		msg += 	"					style=\"width: 600px\">                                                                                                                                                                                                        ";
		msg += 	"					<tbody>                                                                                                                                                                                                                        ";
		msg += 	"						<tr>                                                                                                                                                                                                                       ";
		msg += 	"							<td style=\"font-family: Arial; color: #ffffff; font-size: 11px; padding: 10px;\">                                                                                                                                     ";
		msg += 	"								@1Rango! - Todos os direitos reservados.                                                                                                                                                                           ";
		msg += 	"							</td>                                                                                                                                                                                                                  ";
		msg += 	"							<td style=\"width: 150px\">                                                                                                                                                                                            ";
		msg += 	"								<table align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"                                                                                                                                            ";
		msg += 	"									style=\"width: 100px\">                                                                                                                                                                                        ";
		msg += 	"									<tbody>                                                                                                                                                                                                        ";
		msg += 	"										<tr>                                                                                                                                                                                                       ";
		msg += 	"											<td><img src=\"www.1rango.com.br/img/mail_cad/4.jpg\" border=\"0\"></td> 																															   ";
		msg += 	"											<td><img src=\"www.1rango.com.br/img/mail_cad/5.jpg\" border=\"0\"></td> 																															   ";
		msg += 	"											<td><img src=\"www.1rango.com.br/img/mail_cad/6.jpg\" border=\"0\"></td> 																															   ";
		msg += 	"										</tr>                                                                                                                                                                                                      ";
		msg += 	"									</tbody>                                                                                                                                                                                                       ";
		msg += 	"								</table>                                                                                                                                                                                                           ";
		msg += 	"							</td>                                                                                                                                                                                                                  ";
		msg += 	"						</tr>                                                                                                                                                                                                                      ";
		msg += 	"					</tbody>                                                                                                                                                                                                                       ";
		msg += 	"				</table>                                                                                                                                                                                                                           ";
		msg += 	"			</td>                                                                                                                                                                                                                                  ";
		msg += 	"		</tr>                                                                                                                                                                                                                                      ";
		msg += 	"	</tbody>                                                                                                                                                                                                                                       ";
		msg += 	"</table>                                                                                                                                                                                                                                          ";

		return msg;
		
		
	}
}